### ISSUE TITLE
Minify and uglify all JavaScript in the framework?

### ISSUE THREAD

**Issue by esanzgar** [ebiwd/EBI-Framework#100]
I wonder if all the JavaScript that the EBI-framework provides should be minimised/uglified:

The following files are not currently minimised/uglified:
* script.js
* foundation.js
* foundationExtendEBI.js

**Comment by khawkins98** [comment]
This is a long-time to-do, no reason we shouldn't be able to do in a minor release. 

We've been using [concat-cli](https://www.npmjs.com/package/concat-cli), should also work for the above. 

https://github.com/ebiwd/EBI-Framework/blob/v1.2/package.json#L27

**Comment by khawkins98** [comment]
Status update.

- foundation.js: minified files available in v1.2, v1.3
  - https://www.ebi.ac.uk/web_guidelines/EBI-Framework/v1.2/libraries/foundation-6/js/foundation.min.js
  - https://wwwdev.ebi.ac.uk/web_guidelines/EBI-Framework/v1.3/libraries/foundation-6/js/foundation.min.js
- script.js and foundationExtendEBI.js
  - Currently not planning to do it for v1.2, but on target for v1.3. I think we also need to update the deployment script to make these files so that way we don't have to manually commit them.

**Comment by khawkins98** [comment]
This should now be complete.
