### ISSUE TITLE
Bootstrap compatibility with the existing foundation scripts and styling

### ISSUE THREAD

**Issue by CS76** [ebiwd/EBI-Framework#22]
Creates an issue with the font sizes in the header section @Metabolights 

http://www.ebi.ac.uk/metabolights/

**Comment by khawkins98** [comment]
Just getting to this now -- and I think we may have chatted about the issue in one of the Framework clinics -- but I did want to leave a note that may be of help to your or others using bootstrap.

The shrunken text is due to Bootstrap defining the html text size at 10px, and Foundation specifying 100%. So the font size becomes: 10px.

You can reset this by, and I know it will sound strange, by adding another CSS def of: 

```html { font-size: 100%; }```

As we get more familiar with any other Bootstrap issues, I could see the making of a bootstrap compatibility file.

Let me know if you other bootstrap issues or concerns.
