### ISSUE TITLE
An odd strip of light green appears on the left border of the banner

### ISSUE THREAD

**Issue by ntung** [ebiwd/EBI-Framework#76]
For my very wide screen resolution [2560x1440], an odd strip of light green appears on the left border of the banner, see screenshot below.
![screenshot-11](https://cloud.githubusercontent.com/assets/663341/25002048/30bdcfbc-2040-11e7-8994-6a0df2f51050.png)

The site can be accessed via the following link:
http://wwwdev.ebi.ac.uk/biomodels/jummp-biomodels/
Any helps?

**Comment by khawkins98** [comment]
This is because the framework doesn't scale the background image to cover the space -- instead, the system wants you to set a background colour that matches the left edge of your image.

You can do this with the meta tag based system, in this case:
```
<meta name="ebi-localmasthead-color" content="#254146"> 
```

A bit more background at: https://ebiwd.github.io/EBI-Pattern-library/patterns/meta-copy/

**Comment by ntung** [comment]
Thanks for your help and the attached link @khawkins98. Following the instructions in your comment, I fixed the issue.
If nobody has the same issue as me, I would close the issue.
